const express = require('express');
const nodemailer = require('nodemailer');
const cors = require('cors');
require('dotenv').config();

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Configure Transporter with environment variables
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: Number(process.env.SMTP_PORT) || 587,
  secure: Number(process.env.SMTP_PORT) === 465,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

// Verify SMTP connection on startup
transporter.verify((error) => {
  if (error) {
    console.warn('⚠️ SMTP Warning:', error.message);
    console.warn('👉 Please double-check your .env file to ensure SMTP_USER and SMTP_PASS are set correctly.');
  } else {
    console.log('✓ SMTP Server is ready to send messages');
  }
});

// Health check endpoint
app.get('/api/health', (req, res) => {
  res.status(200).json({ status: 'ok', message: 'RiskGraph AI Alert Service running' });
});

// API endpoint to send fraud alert email
app.post('/api/send-fraud-alert', async (req, res) => {
  try {
    const { 
      transactionId, 
      merchant, 
      amount, 
      dateTime, 
      location, 
      status, 
      riskScore, 
      reason 
    } = req.body;

    const recipient = process.env.NOTIFICATION_RECIPIENT_EMAIL;
    const sender = process.env.SMTP_USER;

    if (!recipient || !sender) {
      console.error('Email trigger failed: SMTP_USER or NOTIFICATION_RECIPIENT_EMAIL is missing in .env');
      return res.status(500).json({ 
        success: false, 
        error: 'Email server configuration missing in .env' 
      });
    }

    const mailOptions = {
      from: `"RiskGraph AI Security" <${sender}>`,
      to: recipient,
      subject: '🚨 RiskGraph AI Fraud Alert – Suspicious Transaction Detected',
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px;">
          <h2 style="color: #d9534f; margin-top: 0;">🚨 Fraud Alert Detected</h2>
          <p>Our fraud protection system detected unusual activity associated with this transaction. The details have been captured below for security review.</p>
          <hr style="border: 0; border-top: 1px solid #eee;" />
          <ul style="list-style-type: none; padding-left: 0;">
            <li style="padding: 6px 0;"><strong>Transaction ID:</strong> ${transactionId || 'N/A'}</li>
            <li style="padding: 6px 0;"><strong>Merchant:</strong> ${merchant || 'N/A'}</li>
            <li style="padding: 6px 0;"><strong>Amount:</strong> ${amount || 'N/A'}</li>
            <li style="padding: 6px 0;"><strong>Date & Time:</strong> ${dateTime || new Date().toLocaleString()}</li>
            <li style="padding: 6px 0;"><strong>Location:</strong> ${location || 'N/A'}</li>
            <li style="padding: 6px 0;"><strong>Status:</strong> <span style="color: #d9534f; font-weight: bold;">${status || 'FLAGGED'}</span></li>
            <li style="padding: 6px 0;"><strong>Risk Score:</strong> ${riskScore ?? 'N/A'}</li>
            <li style="padding: 6px 0;"><strong>Reason / Flag Explanation:</strong> ${reason || 'High risk pattern identified'}</li>
          </ul>
          <hr style="border: 0; border-top: 1px solid #eee;" />
          <p style="font-size: 0.85em; color: #777; margin-bottom: 0;"><em>This is an automated notification generated by RiskGraph AI.</em></p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);
    console.log(`✓ Fraud alert email sent to ${recipient} for Transaction: ${transactionId || 'N/A'}`);
    return res.status(200).json({ success: true, message: 'Alert sent successfully.' });

  } catch (error) {
    console.error('Email sending failed:', error.message);
    return res.status(500).json({ success: false, error: error.message });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`RiskGraph AI Alert Server running on port ${PORT}`);
});